name: "Hello Actions"
description: "Greet Eunsukimme"
author: "eunsukimme@github.com"

inputs:
  GREETING: 
    description: "word to greet"
    required: true
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Eunsu"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book"
  color: "green"
